name: mena
description: Middle East and North Africa country data utilities for Dart/Flutter.
version: 1.0.0
repository: https://github.com/mohamedmaher-dev/mena

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
