name: mena
description: >-
  Comprehensive offline MENA country data with Arabic-first localization, ISO codes,
  currencies, and dial codes. Includes automatic locale switching and Arabic/English support.
version: 1.0.1
homepage: https://github.com/mohamedmaher-dev/mena
repository: https://github.com/mohamedmaher-dev/mena
issue_tracker: https://github.com/mohamedmaher-dev/mena/issues
documentation: https://pub.dev/documentation/mena/latest/

topics:
  - countries
  - mena
  - arabic
  - currency
  - flags

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.9.2

# No runtime dependencies - pure Dart implementation

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

# Additional metadata for better discoverability
funding:
  - https://github.com/sponsors/mohamedmaher-dev
